# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RoS Frontend' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RoS Frontend
  pod 'Alamofire'

  target 'RoS FrontendTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RoS FrontendUITests' do
    # Pods for testing
  end

end
